### ISSUE TITLE
target_port should accept integer from variable

### ISSUE THREAD

**Issue by rahulinux** [ansible/ansible-kubernetes-modules#19]
**Error**

```
"Failed to create object: Service \"hello\" is invalid: spec.ports[0].targetPort: Invalid value: \"8080\": must contain at least one letter or number (a-z, 0-9)"
```
**Example** 

```
    ports:
      - port: "{{  env_vars.PORT | int }}"
        target_port: "{{  env_vars.PORT | int }}"
        name: "{{ name }}"
```

After removing target_port, as per doc, it will use port value, it works. but after re-run playbook, it throw msg `Failed to patch object: unrecognized type: int32`

Why target_port type is str and port type is int ?
