### ISSUE TITLE
k8s_extensions_v1beta1_deployment:  Failed to patch object: unrecognized type: string

### ISSUE THREAD

**Issue by rahulinux** [ansible/ansible-kubernetes-modules#22]
If we redeploy same deployment `k8s_extensions_v1beta1_deployment`, it's throws :  `Failed to patch object: unrecognized type: string`

Deployment example: 

```
- name: Deployment 
  k8s_extensions_v1beta1_deployment:
     state: '{{ state }}' 
     name: grafana 
     namespace: monitoring
     spec_template_metadata_labels:
       app: grafana 
     spec_selector_match_labels:
       app: grafana 
     spec_replicas: 1
     service_account_name: grafana 
     containers:
     - name: grafana 
       image: grafana/grafana:4.5.2 
       ports: 
       - containerPort: 3000
         name: web
       env: 
         - name: GF_AUTH_BASIC_ENABLED
           value: "true"
         - name: GF_AUTH_ANONYMOUS_ENABLED
           value: "false"
         - name: GF_SECURITY_ADMIN_USER
           value_from: 
             secret_key_ref: 
                name: grafana-credentials
                key: user
         - name: GF_SECURITY_ADMIN_PASSWORD
           value_from: 
             secret_key_ref: 
                name: grafana-credentials
                key: password
       resources:
         limits:
           cpu: 200m
           memory: 200Mi
         requests:
           cpu: 100m
           memory: 100Mi
       readiness_probe:
         http_get:
           path: /api/health
           port: 3000
         initial_delay_seconds: 5
         timeout_seconds: 5
       liveness_probe:
         tcp_socket:
            port: 3000
         timeout_seconds: 10
         initial_delay_seconds: 10
     - name: grafana-watcher 
       image:  quay.io/coreos/grafana-watcher:v0.0.8 
       resources:
         limits:
           cpu: 200m
           memory: 100Mi
         requests:
           cpu: 100m
           memory: 50Mi
       env: 
         - name: GRAFANA_USER
           value_from: 
             secret_key_ref: 
                name: grafana-credentials
                key: user
         - name: GRAFANA_PASSWORD
           value_from: 
             secret_key_ref: 
                name: grafana-credentials
                key: password
       args:
       - '--watch-dir=/var/grafana-dashboards-0'
       - '--grafana-url=http://localhost:3000'
       volume_mounts: 
       - name: grafana-dashboards-0
         mount_path: /var/grafana-dashboards-0
     volumes:
     - name: grafana-storage
       empty_dir: 
         medium: {}
     - name: grafana-dashboards-0
       config_map: 
         name: grafana-dashboards-0
```
