### ISSUE TITLE
List k8s kinds

### ISSUE THREAD

**Issue by rahulinux** [ansible/ansible-kubernetes-modules#23]
I'm trying to list deployments using:

```
---
- hosts: localhost
  roles:
     - role: ansible-kubernetes-modules
       install_python_requirements: no

  tasks:
     - k8s_extensions_v1beta1_deployment_list:
         state: present
```
but it throws : `Failed to retrieve requested object: Error: method list_deployment not found for model deployment_list. Did you forget to include the namespace?`

and after adding namespace `Unsupported parameters for (k8s_apps_v1beta1_deployment_list) module: namespace Supported parameters include: api_key,cert_file,context,debug,dry_run,force,host,key_file,kubeconfig,password,resource_definition,src,ssl_ca_cert,state,username,verify_ssl`
