### ISSUE TITLE
Secrets and string_data always changed

### ISSUE THREAD

**Issue by awiddersheim** [ansible/ansible-kubernetes-modules#3]
When working with secrets using these modules it's somewhat convenient to declare things using `string_data` like the following:

```
- name: create example-app secrets
  k8s_v1_secret:
    state: present
    resource_definition:
      metadata:
        name: example-app-config
        namespace: foo
      string_data:
        config.ini: "{{ lookup('template', 'example-app/config.ini.j2') }}"
```

There seem to be some unforeseen idempotency issues with this though. The `k8s_common` module will compare the object set to be changed with any existing objects in kubernetes [here](https://github.com/ansible/ansible-kubernetes-modules/blob/master/module_utils/k8s_common.py#L207-L224). If the secret was already created and Ansible is run again, the comparison happens against the data converted to base64.

This can be avoided by not using `string_data` and using the `b64encode` Ansible filter like so:

```
- name: create example-app secrets
  k8s_v1_secret:
    state: present
    resource_definition:
      metadata:
        name: example-app-config
        namespace: foo
      data:
        config.ini: "{{ lookup('template', 'example-app/config.ini.j2') | b64encode }}"
```

With the above, no changes occur between runs since the data is compared in their ending base64 formats.

It would be nice if the Ansible modules would convert any `string_data` to base64 and adding it to `data` for the secrets module before doing any comparisons.

I'm not sure where the best place to make this change would be. Seems like the modules are generated.

Thought about possibly [here](https://github.com/ansible/ansible-kubernetes-modules/blob/master/module_utils/k8s_common.py#L263). Would love some feedback on this.
