### ISSUE TITLE
Could not find imported module support code

### ISSUE THREAD

**Issue by born2fail** [ansible/ansible-kubernetes-modules#6]
When trying to use the module in a playbook like:
```
---
- hosts: localhost
  remote_user: root
  roles:
    - role: ansible.kubernetes-modules
      install_python_requirements: no
    - role: openshift-prueba
```
I get this error:
```
TASK [openshift-prueba : Create project] **************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "Could not find imported module support code for openshift_v1_project.  Looked for either OpenShiftAnsibleModule.py or openshift_common.py"}

```
